version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "notes_db"
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - notes-network

  notes-backend:
    build: ./backend
    container_name: notes-backend
    ports:
      - "5000:5000"
    networks:
      - notes-network

    env_file:
      - ./backend/.env
      
    depends_on:
      mysql-db:
        condition: 
          service_healthy
          
  nginx:
    image: nginx:alpine

    container_name: notes-nginx

    ports:
     - "8081:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - notes-backend

    networks:
      - notes-network    

volumes:
  mysql-data:

networks:
  notes-network:
    driver: bridge
